name: Cypress E2E

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  stage-tests:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: stage
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run cy:run

#  prod-tests:
#  To be filled